### PR TITLE
Add High Sierra support to prepare_iso.sh

### PR DESCRIPTION
**Pull request by americanhanko**
## This PR

- adds support for High Sierra to `prepare_iso.sh`
- Removes some whitespace, converts tabs to spaces
- A few minor changes suggested by [shellcheck](https://github.com/koalaman/shellcheck)
- Sets checksum values to "none" since Packer warns if there is no checksum or checksum type specified

## Why

- Even though we can't install unsigned packages on anything beyond 10.12.3, I think having this script support High Sierra is still useful.

### CODE REVIEW

**Comment by clburlison** [comment]
For what it's worth I used this PR yesterday to build an iso with High Sierra 👍 . Might be nice to verify against an older OS version.

**Comment by tzeejay** [comment]
@americanhanko Do I get it right that this is just "make this script understand the changes in the High Sierra" installer but outputs a non-bootable iso, because of the signing mess?

**Comment by tzeejay** [comment]
If yes, I just got a little excited.

Thanks for you work anyways. Would like to see this merged

**Comment by camilamacedo86** [comment]
Why was it not merged so far?

**Comment by pietrocaselani** [comment]
Hi everyone!
Any updates here?
Do you consider merging this PR?

**Comment by egandro** [comment]
> Following the test performed.
> ==> virtualbox-iso: Waiting for SSH to become available...

Same issue here with 10.14.2.

No Idea how to fix this. 

I played with the USB -> xhci and the mouse to be USB.

**Comment by itstehkman** [comment]
@timsutton @americanhanko @tzeejay any updates on this PR? I am glad to help and review or make some PRs! think this is also a necessary patch in order to support Mojave as well

**Comment by jfpanisset** [comment]
Starting with 10.14/Mojave BaseSystem.dmg mounts as /Volumes/macOS Base System rather than /Volumes/OS X Base System

**Pull request closed without merging**
