### PR TITLE
Add option to configure auto-login during OS X installation.

### PR DESCRIPTION
**Pull request by iankendrick**
Allow configuring auto-login during OS installation instead of after first boot. In order to use, pass in '-a' to prepare_iso.sh
- python is not available during OS install, so the password is generated during prepare-iso.sh run and then added to the veewee package. 
- gen_kcpassword.py is basically identical to set_kcpassword.py. This could be re-factored but I wanted to minimize the change.
- autologin set-up is in prepare-iso/support/autologin. This file is appended to post-install script when autologin is enabled

This is necessary on ESXi, where mounting vmtools seems to require a desktop session.

### CODE REVIEW

**Comment by timsutton** [comment]
Thanks. When you say "mounting vmtools" however.. is there some better way we could address support for ESXi? Is your use case to have a template that runs the vsphere postprocessor from the vmware-iso build?

**Comment by iankendrick** [comment]
My use case is using ESXi as the builder instead of a workstation version of VMWare. This allows users to build images as long as they have access to an ESXi machine [1]. 

Here's the basic outline of the problem:
- Unlike Fusion, Packer doesn't upload an ISO to ESXi guests during StepUploadTools. Instead it uses an SSH session to ESXi and an ESXi specific command to mount the tools ('vim-cmd vmsc/tools-install"  ) [2]
- For some reason, the ESXi command doesn't do anything if there is just an SSH session on the guest. It only works when a desktop session exists.
- There's no way to re-enter the UploadTools step from the Provision step, so autologin.sh is too late to create the desktop stession.

I'd welcome another approach. ESXi also requires changes to scripts/vmware.sh which I can include in a separate PR.

[1] "Building On A Remote VSphere Hypervisor" at https://www.packer.io/docs/builders/vmware-iso.html
[2] https://github.com/mitchellh/packer/blob/master/builder/vmware/common/step_upload_tools.go
https://github.com/mitchellh/packer/blob/master/builder/vmware/iso/driver_esx5.go#L130

**Comment by timsutton** [comment]
Sorry for the delay - I did finally have some time to set up an ESXi box and see what you mean in terms of how Packer communicates with it.

Just curious of how you use ESXi builds: When your packer build run is finished, is your VM still registered with the host?

Feel free to include your changes to `vmware.sh` in this same pull - I'd consider it related to the change.

**Comment by iankendrick** [comment]
I've added the vmware.sh changes. I don't have a fusion instance to test against, but will try to set one up.

> Just curious of how you use ESXi builds: When your packer build run is finished, is your VM still registered with the host?

No, packer leaves the machine disabled in the inventory and it has to be re-added (either via the vCenter client or the vmware command line tool.) It seems like this is by design.

**Comment by timsutton** [comment]
Sorry to have left this thread hanging - I've considered that it might be simpler for us to simply automate installing the VMware tools within the guest itself as a provision step, à la https://derflounder.wordpress.com/2015/05/10/installing-the-latest-vmware-tools-in-os-x-vms-with-autopkg/.

One issue is that ESXi would report that it's an unsupported version, as this isn't exactly the same flavor of tools as what ESXi ships with for darwin guests. The VMware tools are generally fine in terms of backwards compatibility, though (@rtrouton's also confirmed that these have worked fine for him for a while).

I think this would mean either needing to keep a separate `template-esxi.json`, or use a bunch of user vars, since the parameters for ESXi would be a bit different and we would also need to disable uploading the tools.. unless having ESXi run the mount command would effectively do nothing and continue?

**Comment by timsutton** [comment]
Just to add to this.. another benefit to having a separate template file would be if we need to including any other custom VMX for compatibility with ESX. Not sure how easy that would be to do with conditional user vars, especially if someone needs to tweak those for a different ESX setup.

**Comment by iankendrick** [comment]
> Sorry to have left this thread hanging - I've considered that it might be simpler for us to simply automate installing the VMware tools within the guest itself as a provision step, à la https://derflounder.wordpress.com/2015/05/10/installing-the-latest-vmware-tools-in-os-x-vms-with-autopkg/.

Thanks, this approach wasn't available at the time I created this MR. I agree, it's much cleaner and solves the issue in a builder-agnostic way.

> I think this would mean either needing to keep a separate template-esxi.json, or use a bunch of user vars, since the parameters for ESXi would be a bit different and we would also need to disable uploading the tools.. unless having ESXi run the mount command would effectively do nothing and continue?

This makes sense. Internally, we maintain a separate builder definition (vmware-iso-esxi) in the normal json. ESXi requires a huge set of extra parameters, so it's easier to hard-code some site-specific defaults and avoid polluting the rest of the template with dozens of extra user vars.

Feel free to close this PR.

**Comment by timsutton** [comment]
re: the extra parameters, I'm finding that at a bare minimum I seem to need to set the Ethernet device params explicitly.

Packer makes this:

```
ethernet0.addresstype = "generated"
ethernet0.bsdname = "en0"
ethernet0.connectiontype = "nat"
ethernet0.displayname = "Ethernet"
ethernet0.linkstatepropagation.enable = "FALSE"
ethernet0.pcislotnumber = "33"
ethernet0.present = "TRUE"
ethernet0.virtualdev = "e1000"
ethernet0.wakeonpcktrcv = "FALSE"
```

This has no association with a network, but via Fusion 8 I can delete the card and re-add it, choosing my VM Network, and this results in this getting set:

```
ethernet0.virtualDev = "e1000e"
ethernet0.networkName = "VM Network"
ethernet0.addressType = "static"
ethernet0.present = "TRUE"
ethernet0.address = "00:50:56:31:C7:A0"
```

..and I find that if I remove the ethernet address-related settings it will auto-generate a MAC address:

```
ethernet0.virtualDev = "e1000e"
ethernet0.networkName = "VM Network"
ethernet0.present = "TRUE"
```

Not yet sure I can just add those three VMX lines to my Packer template and it will work, though, if there's other conflicting settings there to begin with.

**Comment by timsutton** [comment]
Looks like it worked. The VMX data I added to my builder entry:

```json
      "vmx_data": {
        "cpuid.coresPerSocket": "1",
        "memsize": "8192",
        "numvcpus": "4",
        "firmware": "efi",
        "keyboardAndMouseProfile": "macProfile",
        "smc.present": "TRUE",
        "hpet0.present": "TRUE",
        "ich7m.present": "TRUE",
        "ehci.present": "TRUE",
        "usb.present": "TRUE",
        "ethernet0.virtualDev": "e1000e",
        "ethernet0.networkName": "VM Network",
        "ethernet0.present": "TRUE"
      }
```

The rest is a holdover from when this project first started so I'm not sure how much of that is still required.

**Comment by timsutton** [comment]
Only issue is now is that after successfully de-registering the VM Packer seems to die on checking the build directory in the datastore:

```
2016/05/27 11:08:25 ui: ==> vmware-iso: Unregistering virtual machine...
==> vmware-iso: Unregistering virtual machine...
2016/05/27 11:08:25 packer: 2016/05/27 11:08:25 opening new ssh session
2016/05/27 11:08:25 packer: 2016/05/27 11:08:25 starting remote command: vim-cmd vmsvc/unregister 2
2016/05/27 11:08:25 packer: 2016/05/27 11:08:25 remote command exited with '0': vim-cmd vmsvc/unregister 2
2016/05/27 11:08:25 ui error: Build 'vmware-iso' errored: lstat output-vmware-iso: no such file or directory
2016/05/27 11:08:25 Builds completed. Waiting on interrupt barrier...
Build 'vmware-iso' errored: lstat output-vmware-iso: no such file or directory
2016/05/27 11:08:25 machine readable: error-count []string{"1"}
2016/05/27 11:08:25 ui error:
==> Some builds didn't complete successfully and had errors:
2016/05/27 11:08:25 machine readable: vmware-iso,error []string{"lstat output-vmware-iso: no such file or directory"}
2016/05/27 11:08:25 ui error: --> vmware-iso: lstat output-vmware-iso: no such file or directory
2016/05/27 11:08:25 ui:
==> Builds finished but no artifacts were created.

2016/05/27 11:08:25 waiting for all plugin processes to complete...
==> Some builds didn't complete successfully and had errors:
--> vmware-iso: lstat output-vmware-iso: no such file or directory

==> Builds finished but no artifacts were created.
```

**Comment by iankendrick** [comment]
I'm now seeing the same thing error with Packer 0.10. I think this was originally tested against 0.8 so I'm not surprised packer upstream has changed.

It looks like the `lstat` issue is addressed by this PR, merged but unreleased:
https://github.com/mitchellh/packer/pull/3050

**Comment by timsutton** [comment]
Thanks for spotting this!

**Pull request closed without merging**
