### PR TITLE
Download & install system updates

### PR DESCRIPTION
**Pull request by radeksimko**
There are certain things that won't work without updated XCode CLI Tools, e.g. compilation of some homebrew formulas (git in particular). I think there's no harm in putting this in.

### CODE REVIEW

**Comment by timsutton** [comment]
Thanks, I've been thinking of adding this step as well.

Since all the other steps are done with included scripts, however, I'd rather not do this inline, but follow the pattern used by the other scripts.

If we could include the documentation of this in the README that would be good too.

**Comment by radeksimko** [comment]
ok, I felt a bit strange with creating one-line file when an `inline` can do, but happy to change the PR as it effectively has no functional impact.

I will also add something into the Readme file.

**Comment by radeksimko** [comment]
Done, I have also refactored the autologic logic as that was inline too. I hope won't mind.

**Comment by timsutton** [comment]
Thanks for refactoring that - it makes the template more organized.

I'll try and run some tests over the next day or so, but looks good at first glance!

I've been annoyed at how the CLI tools install trick (which is already fragile) has weird results lately (#24), and if we're just running `softwareupdate` by default after the tools installation this picks up any stray updates left over from that as well.

**Comment by timsutton** [comment]
Tested and all looks good to me. Merging, finally!

**Pull request merged**
